### ISSUE TITLE
CLI 2.0.0 release checklist

### ISSUE THREAD

**Issue by DavidWells** [netlify/netlify-cli#46]
Checklist for 2.0.0 release

- [ ] Finish `init` command
- [ ] Delete https://github.com/netlify/cli/
- [ ] Rename https://github.com/netlify/netlify-cli/ to https://github.com/netlify/cli/
- [ ] publish docs site to cli.netlify.com
- [ ] Add 2.0.0 release notice to top of https://github.com/netlify/netlifyctl
- [ ] Add 2.0.0 links to https://www.netlify.com/docs/cli/ and update text to point people to https://github.com/netlify/cli/ repo
- [ ] Publish release blog post
- [ ] Share on social medias
